// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-AdAjro9ZwUj1ehbMKJQwGn6fE260QWQ',
    appId: '1:408999501400:web:2faced7f35cf8ff358f42d',
    messagingSenderId: '408999501400',
    projectId: 'new-texi-app',
    authDomain: 'new-texi-app.firebaseapp.com',
    storageBucket: 'new-texi-app.appspot.com',
    measurementId: 'G-WF0TWHH6PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtsuu6re8BaZko4yP4j1ODei6q_ML_bO0',
    appId: '1:408999501400:android:2cce6e789bb9903e58f42d',
    messagingSenderId: '408999501400',
    projectId: 'new-texi-app',
    storageBucket: 'new-texi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSPBTTz_uIFxKpiqW6XE1ScLorMroXCJ4',
    appId: '1:408999501400:ios:bf7a00dd0465a2f258f42d',
    messagingSenderId: '408999501400',
    projectId: 'new-texi-app',
    storageBucket: 'new-texi-app.appspot.com',
    iosClientId: '408999501400-ufkmj61nod2ge7hbj34pmcvsv729kbf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTexiDriver',
  );
}
